import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { JazzClientContext } from "./jazz-client";
import { Account, ID } from "jazz-tools";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const hardcodedUserCredentials = {
  accountID: "co_z9vEwRPyv91S1DjgK7YZrU3L2qQ" as ID<Account>,
  secret: "sealerSecret_z2EYHmgJdUo4eDzYAQV8mz4PFTwnQrZTJCpBSiBiofEgT/signerSecret_z9k8kci8cskPBuRQmQUDKszEH6UJJCHvMzG9rx6Wxvpgh" as const
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <JazzClientContext credentials={hardcodedUserCredentials}>
          {children}
        </JazzClientContext>
      </body>
    </html>
  );
}
